name: Build Service and Push Docker Image

#on:
#  workflow_run:
#    workflows: ["Tenant-Management API Workflow"]
#    types:
#      - completed

on:
  repository_dispatch:
    types: [custom_event_name]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        run: |
          echo "IMAGE_TAG=$(date +%Y-%m-%d)-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/{{SERVICE_NAME}}:${{ env.IMAGE_TAG }}