name: Tenant-Management API Workflow

on: [pull_request]

env:
  SERVICE_NAME: tenant-management-api

jobs:
  code-review-and-test:
    strategy:
      matrix:
        mongodb-version: [ '6.0.5' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      - name: Write Secrets and Environment Variable to Application Configuration File
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'application.yaml'
          fileDir: './infrastructure/config'
          encodedString: ${{ secrets.APPLICATION_PROPERTIES }}

      - name: Setup Go
        uses: actions/setup-go@v4.1.0

      - name: Run Linter
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: info
          golangci_lint_flags: "-E wastedassign -E unconvert -E stylecheck -E revive -E nilerr -E nestif -E ireturn -E gosec"

      - name: Run Unit and Integration Tests
        run: go test -v ./...
