name: Tenant-Management API Workflow

on: [push, pull_request]

env:
  SERVICE_NAME: tenant-management-api

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4.0.0

      - name: Run Linter
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: info
          golangci_lint_flags: "-E wastedassign -E unconvert -E stylecheck -E revive -E nilerr -E nestif -E ireturn -E gosec (gas)"

      - name: Dependency Review
        uses: actions/dependency-review-action@v3.0.4
        with:
          fail-on-severity: moderate

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4.0.0

      - name: Run Unit Tests
        run: go test -v ./...
